version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - PORT=5000
      - DATABASE_URL=postgresql://postgres:T.w.j20012@@db:5432/crimble
      - JWT_SECRET=your_jwt_secret_key_here
      - CLIENT_URL=http://frontend:3000
    depends_on:
      - db
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - crimble-network

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=T.w.j20012@
      - POSTGRES_DB=crimble
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - crimble-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - crimble-network

volumes:
  postgres_data:

networks:
  crimble-network:
    driver: bridge
